from django.db import models
from import_export import widgets
from django.utils import timezone

class Data(models.Model):
    date=models.CharField(null=True,max_length=20)
    h10=models.FloatField(null=True)
    m10=models.FloatField(null=True)
    u10=models.FloatField(null=True)
    z10=models.FloatField(null=True)
    h11=models.FloatField(null=True)
    m11=models.FloatField(null=True)
    u11=models.FloatField(null=True)
    z11=models.FloatField(null=True)
    h12=models.FloatField(null=True)
    m12=models.FloatField(null=True)
    u12=models.FloatField(null=True)
    z12=models.FloatField(null=True)
    h13=models.FloatField(null=True)
    m13=models.FloatField(null=True)
    u13=models.FloatField(null=True)
    z13=models.FloatField(null=True)
    h14=models.FloatField(null=True)
    m14=models.FloatField(null=True)
    u14=models.FloatField(null=True)
    z14=models.FloatField(null=True)
    h15=models.FloatField(null=True)
    m15=models.FloatField(null=True)
    u15=models.FloatField(null=True)
    z15=models.FloatField(null=True)
    h16=models.FloatField(null=True)
    m16=models.FloatField(null=True)
    u16=models.FloatField(null=True)
    z16=models.FloatField(null=True)
    h17=models.FloatField(null=True)
    m17=models.FloatField(null=True)
    u17=models.FloatField(null=True)
    z17=models.FloatField(null=True)
    h18=models.FloatField(null=True)
    m18=models.FloatField(null=True)
    u18=models.FloatField(null=True)
    z18=models.FloatField(null=True)
    h19=models.FloatField(null=True)
    m19=models.FloatField(null=True)
    u19=models.FloatField(null=True)
    z19=models.FloatField(null=True)

    def __str__(self):
        return self.date
