# Generated by Django 3.0.6 on 2020-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outrights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.FloatField(null=True),
        ),
    ]
