# Generated by Django 3.0.6 on 2020-05-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outrights', '0003_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
